### ISSUE TITLE
vert.x 3.5.1 co.paralleluniverse.fibers.instrument.UnableToInstrumentException

### ISSUE THREAD

**Issue by mscofy** [vert-x3/vertx-sync#27]
I update vert.x from version 3.5.0 to 3.5.1,project run with errors, this is my shell

java -javaagent:/Users/xxx/.m2/repository/co/paralleluniverse/quasar-core/0.7.9/quasar-core-0.7.9.jar=b -Dvertx.zookeeper.config=./zookeeper.json -jar target/aaa-fat.jar -conf application-conf.json -cluster

[quasar] ERROR: Unable to instrument class io/vertx/core/impl/DeploymentManager$DeploymentImpl
co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V because of synchronization
at co.paralleluniverse.fibers.instrument.InstrumentMethod.dumpCodeBlock(InstrumentMethod.java:720)
at co.paralleluniverse.fibers.instrument.InstrumentMethod.accept(InstrumentMethod.java:415)
at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:265)
at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:120)
at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:88)
at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:187)
at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:465)
at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:203)
at io.vertx.core.impl.DeploymentManager$$Lambda$45/1076984738.handle(Unknown Source)
at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76)
at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
at io.vertx.core.Starter.runVerticle(Starter.java:328)
at io.vertx.core.Starter.run(Starter.java:138)
at io.vertx.core.Starter.main(Starter.java:96)

**Comment by jponge** [comment]
This kind of error shall not prevent the application to be running fine. Quasar is signaling that it stumbles upon a piece of code using a `synchronized` method so it cannot instrument it.

You may look into http://docs.paralleluniverse.co/quasar/#synchronized for possible configuration tweaks.

**Comment by jponge** [comment]
For the record commit f61aa3a6f9e0bd72165df64d2bfcb29791b10323 introduced that `rollback` method.

**Comment by mscofy** [comment]
But why did it running fine in vertx 3.5.0?

**Comment by mscofy** [comment]
But why did it run fine in vertx 3.5.0?

**Comment by vietj** [comment]
I think because since we changed the implementation of the deployment manager to add a synchronized block to fix a race condition in the implementation

**Comment by mscofy** [comment]
So  can i ignore these error messages?

**Comment by jponge** [comment]
You _should_ be able to ignore them. Is the application still passing tests?

**Comment by mscofy** [comment]
Sorry ,I don't understand what passing tests means?

**Comment by eriknyk** [comment]
same here, but its breaking the app, so the app never runs completely

**Comment by eriknyk** [comment]
same here, but it's breaking the app

```
java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

*vertx.version = 3.5.3*

```
java -javaagent:quasar-core-0.7.10-jdk8.jar -jar demo-vertx-sync-1.0.0-SNAPSHOT-fat.jar
```

```
[quasar] WARNING: UnableToInstrumentException encountered when instrumenting io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V: Unable to instrument io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V because of synchronization
[quasar] ERROR: Unable to instrument class io/vertx/core/impl/DeploymentManager$DeploymentImpl
java.lang.NullPointerException
	at co.paralleluniverse.asm.MethodWriter.visitMaxs(Unknown Source)
	at co.paralleluniverse.asm.tree.MethodNode.accept(Unknown Source)
	at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:260)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:134)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:94)
	at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:209)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:465)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:203)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)
[quasar] ERROR: while transforming io/vertx/core/impl/DeploymentManager$DeploymentImpl: null
java.lang.NullPointerException
	at co.paralleluniverse.asm.MethodWriter.visitMaxs(Unknown Source)
	at co.paralleluniverse.asm.tree.MethodNode.accept(Unknown Source)
	at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:260)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:134)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:94)
	at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:209)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:465)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:203)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)
Exception in Fiber "fiber-vertx.contextScheduler-10000001" java.lang.NoSuchMethodError: co.paralleluniverse.fibers.Stack.popMethod()V
	at io.vertx.ext.sync.SyncVerticle.lambda$start$a7d88694$1(SyncVerticle.java:30)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:44)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:32)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1097)
java.lang.NoSuchMethodError: co.paralleluniverse.fibers.Stack.popMethod()V
	at io.vertx.ext.sync.SyncVerticle.lambda$start$a7d88694$1(SyncVerticle.java:30)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:44)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:32)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1097)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788)
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100)
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91)
	at io.vertx.ext.sync.Sync.lambda$getContextScheduler$2(Sync.java:202)
	at co.paralleluniverse.fibers.FiberExecutorScheduler.execute(FiberExecutorScheduler.java:85)
	at co.paralleluniverse.fibers.RunnableFiberTask.submit(RunnableFiberTask.java:296)
	at co.paralleluniverse.fibers.Fiber.start(Fiber.java:1129)
	at io.vertx.ext.sync.SyncVerticle.start(SyncVerticle.java:30)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Sep 07, 2018 6:45:31 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
java.lang.NoSuchMethodError: co.paralleluniverse.fibers.Stack.popMethod()V
	at io.vertx.ext.sync.SyncVerticle.lambda$start$a7d88694$1(SyncVerticle.java:30)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:44)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:32)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1097)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788)
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100)
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91)
	at io.vertx.ext.sync.Sync.lambda$getContextScheduler$2(Sync.java:202)
	at co.paralleluniverse.fibers.FiberExecutorScheduler.execute(FiberExecutorScheduler.java:85)
	at co.paralleluniverse.fibers.RunnableFiberTask.submit(RunnableFiberTask.java:296)
	at co.paralleluniverse.fibers.Fiber.start(Fiber.java:1129)
	at io.vertx.ext.sync.SyncVerticle.start(SyncVerticle.java:30)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

java.lang.NoSuchMethodError: co.paralleluniverse.fibers.Stack.popMethod()V
	at io.vertx.ext.sync.SyncVerticle.lambda$start$a7d88694$1(SyncVerticle.java:30)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:44)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:32)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1097)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788)
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100)
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91)
	at io.vertx.ext.sync.Sync.lambda$getContextScheduler$2(Sync.java:202)
	at co.paralleluniverse.fibers.FiberExecutorScheduler.execute(FiberExecutorScheduler.java:85)
	at co.paralleluniverse.fibers.RunnableFiberTask.submit(RunnableFiberTask.java:296)
	at co.paralleluniverse.fibers.Fiber.start(Fiber.java:1129)
	at io.vertx.ext.sync.SyncVerticle.start(SyncVerticle.java:30)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by eriknyk** [comment]
I've created the repo that reproduce the error above,

https://github.com/eriknyk/demo-vertx-sync

Regards.

**Comment by fperie** [comment]
With the PR #31 (https://github.com/vert-x3/vertx-sync/pull/31), vertx used the quasar last version available on jdk8.
Now, should not this issue also be corrected?
@jponge @vietj

**Comment by fperie** [comment]
Hello @vietj, @jponge, 

Even with the quasar last version (0.7.10), the issue is still there with vertx 3.6.0-SNAPSHOT but that doesn't fail the unit tests of the project.

```
[quasar] WARNING: UnableToInstrumentException encountered when instrumenting io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextInternal;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V: Unable to instrument io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextInternal;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V because of synchronization
[quasar] ERROR: Unable to instrument class io/vertx/core/impl/DeploymentManager$DeploymentImpl
java.lang.NullPointerException
        at co.paralleluniverse.asm.MethodWriter.visitMaxs(Unknown Source)
        at co.paralleluniverse.asm.tree.MethodNode.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:260)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:134)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:94)
        at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:209)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
```

**Comment by dazraf** [comment]
Hi @jponge @vietj 

Can we please re-open this ticket? 
Seeing this exact same error with vertx 3.7.1 and quasar 0.7.10.

**Comment by ando0689** [comment]
I have the same issue with vertx 3.7.1 and quasar 0.7.10.

**Comment by osancus** [comment]
Facing same error with vertx 3.7.1 and quasar 0.7.10.

[quasar] ERROR: Unable to instrument class io/vertx/core/impl/DeploymentManager$DeploymentImpl

**Comment by vietj** [comment]
can somebody provide a reproducer test for this project's test suite ? that would help to fix it.

**Comment by laodaocheney** [comment]
I have the same issue with vertx 3.8.5 and quasar 0.7.10.
